# Generated by Django 5.2 on 2025-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_wastereport_wastereportimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='wastereport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
