# Generated by Django 5.2 on 2025-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_wastereport_longtitude_wastereport_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=11),
        ),
    ]
