# Generated by Django 5.2 on 2025-06-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_wastereport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=20),
        ),
    ]
