# Generated by Django 5.2 on 2025-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_wastereport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='category',
            field=models.CharField(choices=[('kitchen waste', 'Kitchen Waste'), ('chemical waste', 'Chemical Waste'), ('organic waste', 'Organic Waste'), ('recycleable waste', 'Recycleable Waste'), ('non-recycleable waste', 'Non-Recycleable Waste'), ('construction waste', 'Construction Waste'), ('medical waste', 'Medical Waste'), ('nuclear waste', 'Nuclear Waste')], default='Kitchen Waste', max_length=25),
            preserve_default=False,
        ),
    ]
